name = "src"
main = "src/worker.ts"
compatibility_date = "2023-09-28"

# node_compat is required to get this warning to go away:
# ✘ [ERROR] Could not resolve "node:net"

#     src/foo.ts:4:28:
#       4 │         const net = require('node:net');
#         ╵                             ~~~~~~~~~~

#   The package "node:net" wasn't found on the file system but is built into node.
#   Add "node_compat = true" to your wrangler.toml file to enable Node.js compatibility.

node_compat = true